routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/auth/login');
});

Auth::routes();

Route::group(['namespace' => 'Dashboard', 'prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home.index');

    // Route Medicine
    Route::resource('medicines', 'MedicineController');
    Route::get('medicine/delete/{id}', 'MedicineController@destroy')->name('medicine.delete');
    Route::get('medicine/trash', 'MedicineController@trash')->name('medicine.trash');
    Route::get('medicine/restore/{id}', 'MedicineController@restore')->name('medicine.restore');
    Route::get('medicine/permanentDelete/{id}', 'MedicineController@permanentDelete')->name('medicine.permanentDelete');

    // Route Medicine Suppliers 
    Route::resource('medicine-suppliers', 'MedicineSupplierController');
    Route::get('medicine-supplier/trash', 'MedicineSupplierController@trash')->name('medicine-supplier.trash');
    Route::get('medicine-supplier/restore/{id}', 'MedicineSupplierController@restore')->name('medicine-supplier.restore');
    Route::get('medicine-supplier/permanentDelete/{id}', 'MedicineSupplierController@permanentDelete')->name('medicine-supplier.permanentDelete');


    // Route Medicine Categories
    Route::resource('medicine-categories', 'MedicineCategoryController');
    Route::get('medicine-category/trash', 'MedicineCategoryController@trash')->name('medicine-category.trash');
    Route::get('medicine-category/restore/{id}', 'MedicineCategoryController@restore')->name('medicine-category.restore');
    Route::get('medicine-category/permanentDelete/{id}', 'MedicineCategoryController@permanentDelete')->name('medicine-category.permanentDelete');

    // Route Medicine Units
    Route::resource('medicine-units', 'MedicineUnitController');
    Route::get('medicine-unit/trash', 'MedicineUnitController@trash')->name('medicine-unit.trash');
    Route::get('medicine-unit/restore/{id}', 'MedicineUnitController@restore')->name('medicine-unit.restore');
    Route::get('medicine-unit/permanentDelete/{id}', 'MedicineUnitController@permanentDelete')->name('medicine-unit.permanentDelete');

    // Route Medicine Return Categories 
    Route::resource('medicine-return-categories', 'MedicineReturCategoryController');
    Route::get('medicine-return-category/trash', 'MedicineReturCategoryController@trash')->name('medicine-return-category.trash');
    Route::get('medicine-return-category/restore/{id}', 'MedicineReturCategoryController@restore')->name('medicine-return-category.restore');
    Route::get('medicine-return-category/permanentDelete/{id}', 'MedicineReturCategoryController@permanentDelete')->name('medicine-return-category.permanentDelete');

    // Route Medicine Retur
    Route::resource('medicine-return', 'MedicineReturController');
    Route::get('medicine-return/all-expired/{id}', 'MedicineReturController@allExpired')->name('medicine-return.all.expired');
    Route::get('medicine-return-check/', 'MedicineReturController@checkExpired')->name('medicine-return.check.expired');
    Route::get('medicine-return-rollback/{id}', 'MedicineReturController@update')->name('medicine-return.rollback');

    // Route medicine retur report
    Route::get('medicine-return-report/index', 'MedicineReturnReportController@index')->name('medicine-return-report.index');
    Route::get('medicine-return-report/search', 'MedicineReturnReportController@search')->name('medicine-return-report.search');
    Route::get('medicine-return-report/print_pdf/{from}/{to}', 'MedicineReturnReportController@print_pdf')->name('medicine-return-report.print_pdf');

    // Route Point Of Sales
    Route::get('/sales', 'PurchaseItemController@index')->name('sales.index');
    Route::post('/sales/addmedicine/{id}', 'PurchaseItemController@addMedicineCart')->name('sales.addmedicine');
    Route::post('/sales/removemedicine/{id}', 'PurchaseItemController@removeMedicineCart');
    Route::post('/sales/increasecart/{id}', 'PurchaseItemController@increasecart');
    Route::post('/sales/decreasecart/{id}', 'PurchaseItemController@decreasecart');
    Route::post('/sales/clear', 'PurchaseItemController@clear');
    Route::post('/sales/bayar', 'PurchaseItemController@bayar');
    Route::get('/sales/history', 'PurchaseItemController@history')->name('sales.history');
    Route::get('/sales/invoice/{id}', 'PurchaseItemController@invoice')->name('sales.invoice');

    // Route Kategori Pengeluaran
    Route::resource('expense-categories', 'ExpenseCategoryController');
    Route::get('expense-category/trash', 'ExpenseCategoryController@trash')->name('expense-category.trash');
    Route::get('expense-category/restore/{id}', 'ExpenseCategoryController@restore')->name('expense-category.restore');
    Route::get('expense-category/permanentDelete/{id}', 'ExpenseCategoryController@permanentDelete')->name('expense-category.permanentDelete');

    // Route Kategori Pendapatan
    Route::resource('income-categories', 'IncomeCategoryController');
    Route::get('income-category/trash', 'IncomeCategoryController@trash')->name('income-category.trash');
    Route::get('income-category/restore/{id}', 'IncomeCategoryController@restore')->name('income-category.restore');
    Route::get('income-category/permanentDelete/{id}', 'IncomeCategoryController@permanentDelete')->name('income-category.permanentDelete');

    // Route Pengeluaran
    Route::resource('expenses', 'ExpenseController');
    Route::get('expense/trash', 'ExpenseController@trash')->name('expense.trash');
    Route::get('expense/restore/{id}', 'ExpenseController@restore')->name('expense.restore');
    Route::get('expense/permanentDelete/{id}', 'ExpenseController@permanentDelete')->name('expense.permanentDelete');

    // Route Pengeluaran
    Route::resource('incomes', 'IncomeController');
    Route::get('income/trash', 'IncomeController@trash')->name('income.trash');
    Route::get('income/restore/{id}', 'IncomeController@restore')->name('income.restore');
    Route::get('income/permanentDelete/{id}', 'IncomeController@permanentDelete')->name('income.permanentDelete');

    // Route Laporan Profit
    Route::get('financial-reports', 'FinancialReportController@index')->name('financial-reports.index');
    Route::get('financial-reports/search', 'FinancialReportController@search')->name('financial-reports.search');
    Route::get('financial-reports/print_pdf/{from}/{to}', 'FinancialReportController@print_pdf')->name('financial-reports.print_pdf');

    // User Management
    // Route::resource('permissions', 'PermissionsController');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
});

app/Http/Controllers/Dashboard/MedicineCategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\MedicineCategory;

class MedicineCategoryController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:Akses Manajemen Produk', ['only' => ['index', 'show', 'create', 'store', 'edit', 'update', 'destroy', 'trash', 'restore', 'permanentDelete']]);
    }

    // function __construct()
    // {
    //     $this->middleware('permission:medicine-categories-list', ['only' => ['index']]);
    //     $this->middleware('permission:medicine-categories-create', ['only' => ['create', 'store']]);
    //     $this->middleware('permission:medicine-categories-edit', ['only' => ['edit', 'update']]);
    //     $this->middleware('permission:medicine-categories-delete', ['only' => ['destroy']]);
    //     $this->middleware('permission:medicine-categories-trash', ['only' => ['trash']]);
    //     $this->middleware('permission:medicine-categories-restore', ['only' => ['restore']]);
    //     $this->middleware('permission:medicine-categories-permanentDelete', ['only' => ['permanentDelete']]);
    // }

    public function index()
    {
        $medicineCategories = MedicineCategory::all();
        return view('dashboard.productManagement.medicineCategories.index', compact('medicineCategories'))->with('no');
    }

    public function create()
    {
        return view('dashboard.productManagement.medicineCategories.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:medicine_categories,name',
        ]);

        MedicineCategory::create($request->all());

        $message = 'Data kategori obat berhasil ditambahkan';
        return redirect()->route('medicine-categories.index')->with('success', $message);
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $medicineCategories = MedicineCategory::find($id);
        return view('dashboard.productManagement.medicineCategories.edit', compact('medicineCategories'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|unique:medicine_categories,name',

        ]);

        $medicineCategories = MedicineCategory::find($id);
        $medicineCategories->name = $request->input('name');
        $medicineCategories->save();
        $message = 'Data kategori obat berhasil diperbaruhi';
        return redirect()->route('medicine-categories.index')->with('success', $message);
    }

    public function destroy($id)
    {
        $medicineCategories = MedicineCategory::find($id);
        $medicineCategories->delete();
        $message = "Data kategori obat berhasil dihapus";
        return redirect()->back()->with('success', $message);
    }

    public function trash()
    {
        $medicineCategories = MedicineCategory::onlyTrashed()->get();
        return view('dashboard.productManagement.medicineCategories.trash', compact('medicineCategories'))->with('no');
    }

    public function restore($id)
    {
        $medicineCategories = MedicineCategory::onlyTrashed()->where('id', $id);
        $medicineCategories->restore();
        $message = "Data kategori obat berhasil dipulihkan";
        return redirect()->route('medicine-categories.index')->with('success', $message);
    }

    public function permanentDelete($id)
    {
        $medicineCategories = MedicineCategory::onlyTrashed()->where('id', $id);
        $medicineCategories->forceDelete();
        $message = "Data kategori obat berhasil dihapus permanent";
        return redirect()->back()->with('success', $message);
    }
}

resources/views/dashboard/productManagement/medicineCategories/create.blade.php
@extends('layouts.dashboard')
@section('title', 'Tambah Kategori Obat')
@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="mb-1 page-title text-truncate text-dark font-weight-medium">Tambah Kategori Obat</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="p-0 m-0 breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('home.index')}}" class="text-muted">Beranda</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('medicine-categories.index')}}" class="text-muted">Kategori Obat</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Tambah Kategori Obatt</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card border-info">
                <div class="card-header bg-info">
                    <h4 class="mb-0 text-white">Form Tambah Kategori Obat</h4>
                </div>
                <div class="card-body">
                    @if(count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Warning!</strong> There were some problems with your input.
                        <br><br>
                        <ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>
                    </div>
                    @endif
                    <form method="POST" action="{{ route('medicine-categories.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-body">
                            <div class="form-group">
                                <label for="name">Nama</label>
                                <input class="form-control" type="text" name="name" id="name" placeholder="Nama Kategori" value="{{ old('name', '') }}">
                            </div>
                        </div>
                        <div class="form-actions">
                            <div class="text-left">
                                <button type="submit" class="btn btn-success">
                                    <i class="far fa-save"> Simpan</i>
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    <i class="far fa-window-close"> Setel Ulang</i>
                                </button>
                                <a class="btn btn-dark" href="{{ route('medicine-categories.index') }}">
                                    <i class="far fa-arrow-alt-circle-left"> Kembali </i>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/productManagement/medicineCategories/edit.blade.php
@extends('layouts.dashboard')
@section('title', 'Edit Kategori Obat')
@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Ubah Kategori Obat</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="{{ route('home.index')}}" class="text-muted">Beranda</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('medicine-categories.index')}}" class="text-muted">Kategori Obat</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Ubah Kategori Obat</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card border-info">
                <div class="card-header bg-info">
                    <h4 class="mb-0 text-white">Formulir Ubah Kategori Obat</h4>
                </div>
                <div class="card-body">
                    @if(count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Warning!</strong> There were some problems with your input.
                        <br><br>
                        <ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>
                    </div>
                    @endif
                    <form method="POST" action="{{ route('medicine-categories.update', $medicineCategories->id) }}" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input class="form-control" type="text" name="name" id="name" value="{{ old('name', $medicineCategories->name) }}">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">
                                <i class="far fa-save"> Simpan</i>
                            </button>
                            <button type="reset" class="btn btn-danger">
                                <i class="far fa-window-close"> Setel Ulang</i>
                            </button>
                            <a class="btn btn-dark" href="{{ route('medicine-categories.index') }}">
                                <i class="far fa-arrow-alt-circle-left"> Kembali </i>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/productManagement/medicineCategories/index.blade.php
@extends('layouts.dashboard')
@section('title', 'Kategori Obat')
@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="mb-1 page-title text-truncate text-dark font-weight-medium">Kategori</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="p-0 m-0 breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('home.index')}}" class="text-muted">Beranda</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Kategori Obat</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

@if(Session::has('success'))
<div class="page-breadcrumb">
    @include('layouts.flash-success',[ 'message'=> Session('success') ])
</div>
@endif

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Daftar Kategori Obat</h4>
                    <div style="margin-bottom: 10px;" class="row">
                        <div class="col-lg-12">
                            <a class="btn btn-success" href="{{ route('medicine-categories.create') }}">
                                <i class="far fa-plus-square"> Tambah Kategori Obat</i>
                            </a>
                            <a class="btn btn-dark" href="{{ route('medicine-category.trash') }}">
                                <i class="far fa-trash-alt"> Tong Sampah</i>
                            </a>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-bordered no-wrap">
                            <thead>
                                <tr>
                                    <th>
                                        No
                                    </th>
                                    <th>
                                        Nama
                                    </th>
                                    <th class="text-center">
                                        Tindakan
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($medicineCategories as $medicineCategory)
                                <tr>
                                    <td>
                                        {{ ++$no ?? ''}}
                                    </td>
                                    <td>
                                        {{ $medicineCategory->name ?? ''}}
                                    </td>
                                    <td class="text-center">
                                        <a class="btn btn-xs btn-info" href="{{ route('medicine-categories.edit', $medicineCategory->id) }}">
                                            <i class="far fa-edit"> Ubah</i>
                                        </a>
                                        <form action="{{ route('medicine-categories.destroy', $medicineCategory->id) }}" method="POST" onsubmit="return confirm('Apakah anda yakin ?');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button type="submit" class="btn btn-danger"> <i class="far fa-window-close"> Pindah Ke Tong Sampah</i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>
@endsection

resources/views/dashboard/productManagement/medicineCategories/trash.blade.php
@extends('layouts.dashboard')
@section('title', 'Tong Sampah Kategori')
@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Tong Sampah</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="{{ route('home.index')}}" class="text-muted">Beranda</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('medicine-categories.index')}}" class="text-muted">Kategori Obat</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Tong Sampah</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

@if(Session::has('success'))
<div class="page-breadcrumb">
    @include('layouts.flash-success',[ 'message'=> Session('success') ])
</div>
@endif

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Sampah</h4>
                    <div style="margin-bottom: 10px;" class="row">
                        <div class="col-lg-12">
                            <a class="btn btn-dark" href="{{ route('medicine-categories.index') }}">
                                <i class="far fa-arrow-alt-circle-left"> Kembali </i>
                            </a>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-bordered no-wrap">
                            <thead>
                                <tr>
                                    <th width="10">
                                        No
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($medicineCategories as $medicineCategory)
                                <tr data-entry-id="{{ $medicineCategory->id }}">
                                    <td>
                                        {{ $no++ ?? '' }}
                                    </td>
                                    <td>
                                        {{ $medicineCategory->name ?? '' }}
                                    </td>

                                    <td>
                                        <a class="btn btn-xs btn-primary" href="{{ route('medicine-category.restore', $medicineCategory->id) }}">
                                            <i class="far fa-window-restore"> Pulihkan</i>
                                        </a>
                                        <a class="btn btn-xs btn-danger" href="{{ route('medicine-category.permanentDelete', $medicineCategory->id) }}">
                                            <i class="far fa-trash-alt"> Hapus Permanen</i>
                                        </a>

                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection