routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('/auth/login');
});

Auth::routes();

Route::group(['namespace' => 'Dashboard', 'prefix' => 'dashboard', 'middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home.index');

    // Route Medicine
    Route::resource('medicines', 'MedicineController');
    Route::get('medicine/delete/{id}', 'MedicineController@destroy')->name('medicine.delete');
    Route::get('medicine/trash', 'MedicineController@trash')->name('medicine.trash');
    Route::get('medicine/restore/{id}', 'MedicineController@restore')->name('medicine.restore');
    Route::get('medicine/permanentDelete/{id}', 'MedicineController@permanentDelete')->name('medicine.permanentDelete');

    // Route Medicine Suppliers 
    Route::resource('medicine-suppliers', 'MedicineSupplierController');
    Route::get('medicine-supplier/trash', 'MedicineSupplierController@trash')->name('medicine-supplier.trash');
    Route::get('medicine-supplier/restore/{id}', 'MedicineSupplierController@restore')->name('medicine-supplier.restore');
    Route::get('medicine-supplier/permanentDelete/{id}', 'MedicineSupplierController@permanentDelete')->name('medicine-supplier.permanentDelete');


    // Route Medicine Categories
    Route::resource('medicine-categories', 'MedicineCategoryController');
    Route::get('medicine-category/trash', 'MedicineCategoryController@trash')->name('medicine-category.trash');
    Route::get('medicine-category/restore/{id}', 'MedicineCategoryController@restore')->name('medicine-category.restore');
    Route::get('medicine-category/permanentDelete/{id}', 'MedicineCategoryController@permanentDelete')->name('medicine-category.permanentDelete');

    // Route Medicine Units
    Route::resource('medicine-units', 'MedicineUnitController');
    Route::get('medicine-unit/trash', 'MedicineUnitController@trash')->name('medicine-unit.trash');
    Route::get('medicine-unit/restore/{id}', 'MedicineUnitController@restore')->name('medicine-unit.restore');
    Route::get('medicine-unit/permanentDelete/{id}', 'MedicineUnitController@permanentDelete')->name('medicine-unit.permanentDelete');

    // Route Medicine Return Categories 
    Route::resource('medicine-return-categories', 'MedicineReturCategoryController');
    Route::get('medicine-return-category/trash', 'MedicineReturCategoryController@trash')->name('medicine-return-category.trash');
    Route::get('medicine-return-category/restore/{id}', 'MedicineReturCategoryController@restore')->name('medicine-return-category.restore');
    Route::get('medicine-return-category/permanentDelete/{id}', 'MedicineReturCategoryController@permanentDelete')->name('medicine-return-category.permanentDelete');

    // Route Medicine Retur
    Route::resource('medicine-return', 'MedicineReturController');
    Route::get('medicine-return/all-expired/{id}', 'MedicineReturController@allExpired')->name('medicine-return.all.expired');
    Route::get('medicine-return-check/', 'MedicineReturController@checkExpired')->name('medicine-return.check.expired');
    Route::get('medicine-return-rollback/{id}', 'MedicineReturController@update')->name('medicine-return.rollback');

    // Route medicine retur report
    Route::get('medicine-return-report/index', 'MedicineReturnReportController@index')->name('medicine-return-report.index');
    Route::get('medicine-return-report/search', 'MedicineReturnReportController@search')->name('medicine-return-report.search');
    Route::get('medicine-return-report/print_pdf/{from}/{to}', 'MedicineReturnReportController@print_pdf')->name('medicine-return-report.print_pdf');

    // Route Point Of Sales
    Route::get('/sales', 'PurchaseItemController@index')->name('sales.index');
    Route::post('/sales/addmedicine/{id}', 'PurchaseItemController@addMedicineCart')->name('sales.addmedicine');
    Route::post('/sales/removemedicine/{id}', 'PurchaseItemController@removeMedicineCart');
    Route::post('/sales/increasecart/{id}', 'PurchaseItemController@increasecart');
    Route::post('/sales/decreasecart/{id}', 'PurchaseItemController@decreasecart');
    Route::post('/sales/clear', 'PurchaseItemController@clear');
    Route::post('/sales/bayar', 'PurchaseItemController@bayar');
    Route::get('/sales/history', 'PurchaseItemController@history')->name('sales.history');
    Route::get('/sales/invoice/{id}', 'PurchaseItemController@invoice')->name('sales.invoice');

    // Route Kategori Pengeluaran
    Route::resource('expense-categories', 'ExpenseCategoryController');
    Route::get('expense-category/trash', 'ExpenseCategoryController@trash')->name('expense-category.trash');
    Route::get('expense-category/restore/{id}', 'ExpenseCategoryController@restore')->name('expense-category.restore');
    Route::get('expense-category/permanentDelete/{id}', 'ExpenseCategoryController@permanentDelete')->name('expense-category.permanentDelete');

    // Route Kategori Pendapatan
    Route::resource('income-categories', 'IncomeCategoryController');
    Route::get('income-category/trash', 'IncomeCategoryController@trash')->name('income-category.trash');
    Route::get('income-category/restore/{id}', 'IncomeCategoryController@restore')->name('income-category.restore');
    Route::get('income-category/permanentDelete/{id}', 'IncomeCategoryController@permanentDelete')->name('income-category.permanentDelete');

    // Route Pengeluaran
    Route::resource('expenses', 'ExpenseController');
    Route::get('expense/trash', 'ExpenseController@trash')->name('expense.trash');
    Route::get('expense/restore/{id}', 'ExpenseController@restore')->name('expense.restore');
    Route::get('expense/permanentDelete/{id}', 'ExpenseController@permanentDelete')->name('expense.permanentDelete');

    // Route Pengeluaran
    Route::resource('incomes', 'IncomeController');
    Route::get('income/trash', 'IncomeController@trash')->name('income.trash');
    Route::get('income/restore/{id}', 'IncomeController@restore')->name('income.restore');
    Route::get('income/permanentDelete/{id}', 'IncomeController@permanentDelete')->name('income.permanentDelete');

    // Route Laporan Profit
    Route::get('financial-reports', 'FinancialReportController@index')->name('financial-reports.index');
    Route::get('financial-reports/search', 'FinancialReportController@search')->name('financial-reports.search');
    Route::get('financial-reports/print_pdf/{from}/{to}', 'FinancialReportController@print_pdf')->name('financial-reports.print_pdf');

    // User Management
    // Route::resource('permissions', 'PermissionsController');
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController');
});

app/Http/Controllers/Dashboard/IncomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Model\Income;
use App\Model\IncomeCategory;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class IncomeController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:Akses Manajemen Biaya', ['only' => ['index', 'show', 'create', 'store', 'edit', 'update', 'destroy', 'trash', 'restore', 'permanentDelete']]);
    }

    // function __construct()
    // {
    //     $this->middleware('permission:income-list', ['only' => ['index']]);
    //     $this->middleware('permission:income-create', ['only' => ['create', 'store']]);
    //     $this->middleware('permission:income-edit', ['only' => ['edit', 'update']]);
    //     $this->middleware('permission:income-delete', ['only' => ['destroy']]);
    //     $this->middleware('permission:income-trash', ['only' => ['trash']]);
    //     $this->middleware('permission:income-restore', ['only' => ['restore']]);
    //     $this->middleware('permission:income-permanentDelete', ['only' => ['permanentDelete']]);
    // }

    public function index()
    {
        $incomes = Income::with(['income_category'])->get();
        return view('dashboard.financialManagement.incomes.index', compact('incomes'))->with('no');
    }

    public function create()
    {
        $income_categories = IncomeCategory::all()->pluck('name', 'id')->prepend(trans('Pilih Kategori'), '');
        return view('dashboard.financialManagement.incomes.create', compact('income_categories'));
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'income_category_id' => 'required',
            'entry_date' => 'required',
            'amount' => 'required',
            'description' => '',
        ]);

        Income::create([
            'user_id' => Auth::id(),
            'income_category_id' => $request->income_category_id,
            'entry_date' => $request->entry_date,
            'amount' => $request->amount,
            'description' => $request->description,
        ]);
        $message = 'Data pendapatan berhasil ditambahkan';
        return redirect()->route('incomes.index')->with('success', $message);
    }


    public function show(Income $income)
    {
        $income->load('income_category');
        return view('dashboard.financialManagement.incomes.show', compact('income'));
    }


    public function edit($id)
    {
        $incomes = Income::find($id);
        $income_categories = IncomeCategory::all()->pluck('name', 'id')->prepend(trans('Pilih Kategori'), '');
        $incomes->load('income_category');
        return view('dashboard.financialManagement.incomes.edit', compact('income_categories', 'incomes'));
    }


    public function update(Request $request, $id)
    {

        $this->validate($request, [
            'income_category_id' => '',
            'entry_date' => 'required',
            'amount' => 'required',
            'description' => '',

        ]);

        $incomes  = Income::find($id);
        $incomes->income_category_id = $request->input('income_category_id');
        $incomes->entry_date = $request->input('entry_date');
        $incomes->amount = $request->input('amount');
        $incomes->description = $request->input('description');
        $incomes->save();
        $message = 'Data pendapatan berhasil diperbaruhi';
        return redirect()->route('incomes.index')->with('success', $message);
    }


    public function destroy($id)
    {
        $incomes = Income::find($id);
        $incomes->delete();
        $message = "Data pendapatan berhasil dihapus";
        return redirect()->back()->with('success', $message);
    }

    public function trash()
    {
        $incomes = Income::onlyTrashed()->get();
        return view('dashboard.financialManagement.incomes.trash', compact('incomes'))->with('no');
    }

    public function restore($id)
    {
        $incomes = Income::onlyTrashed()->where('id', $id);
        $incomes->restore();
        $message = "Data pendapatan berhasil dipulihkan";
        return redirect()->route('incomes.index')->with('success', $message);
    }

    public function permanentDelete($id)
    {
        $expense = Income::onlyTrashed()->where('id', $id);
        $expense->forceDelete();
        $message = "Data pendapatan berhasil dihapus permanent";
        return redirect()->back()->with('success', $message);
    }
}

resources/views/dashboard/financialManagement/incomes/create.blade.php
@extends('layouts.dashboard')
@section('title', 'Tambah Pendapatan')
@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="mb-1 page-title text-truncate text-dark font-weight-medium">Tambah Pendapatan</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="p-0 m-0 breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('home.index')}}" class="text-muted">Beranda</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('incomes.index')}}" class="text-muted">Pendapatan</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Tambah Pendapatan</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="card border-info">
                <div class="card-header bg-info">
                    <h4 class="mb-0 text-white">Formulir Tambah Pendapatan</h4>
                </div>
                <div class="card-body">
                    @if(count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Warning!</strong> There were some problems with your input.
                        <br><br>
                        <ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>
                    </div>
                    @endif
                    <form method="POST" action="{{ route('incomes.store') }}">
                        @csrf
                        <div class="form-group">
                            <label for="income_category_id">Kategori Pendapatan</label>
                            <select class="form-control select2" name="income_category_id" id="income_category_id">
                                @foreach($income_categories as $id => $income_category)
                                <option value="{{ $id }}" {{ old('income_category_id') == $id ? 'selected' : '' }} required>{{ $income_category }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="required" for="entry_date">Tanggal</label>
                            <input type="date" class="form-control" value="{{ old('entry_date') }}" name="entry_date" id="entry_date">
                        </div>
                        <div class="form-group">
                            <label class="required" for="amount">Biaya</label>
                            <input class="form-control" type="number" name="amount" id="amount" value="{{ old('amount', '') }}" step="0.01" placeholder="Contoh : 1000">
                        </div>
                        <div class="form-group">
                            <label for="description">Deskripsi</label>
                            <input class="form-control" type="text" name="description" id="description" value="{{ old('description', '') }}">
                        </div>
                        <div class="form-actions mt-5">
                            <button class="btn btn-success" type="submit">
                                <i class="far fa-save"> Simpan</i>
                            </button>
                            <button type="reset" class="btn btn-danger">
                                <i class="far fa-window-close"> Setel Ulang</i>
                            </button>
                            <a class="btn btn-dark" href="{{ route('incomes.index') }}">
                                <i class="far fa-arrow-alt-circle-left"> Kembali </i>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/financialManagement/incomes/edit.blade.php
@extends('layouts.dashboard')
@section('title', 'Ubah Pendapatan')
@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Ubah Pendapatan</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="{{ route('home.index')}}" class="text-muted">Beranda</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('incomes.index')}}" class="text-muted">Pendapatan</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Ubah Pendapatan</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="card border-info">
                <div class="card-header bg-info">
                    <h4 class="mb-0 text-white">Formulir Ubah Pendapatan</h4>
                </div>
                <div class="card-body">
                    @if(count($errors) > 0)
                    <div class="alert alert-danger">
                        <strong>Warning!</strong> There were some problems with your input.
                        <br><br>
                        <ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>
                    </div>
                    @endif
                    <form method="POST" action="{{ route('incomes.update', $incomes->id) }}">
                        @method('PUT')
                        @csrf
                        <div class="form-group">
                            <label for="income_category_id">Kategori Pendapatan</label>
                            <select class="form-control select2" name="income_category_id" id="income_category_id">
                                @foreach($income_categories as $id => $income_category)
                                <option value="{{ $id }}" {{ (old('income_category_id') ? old('income_category_id') : $incomes->income_category->id ?? '') == $id ? 'selected' : '' }}>{{ $income_category ?? ''  }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label class="required" for="entry_date">Tanggal</label>
                            <input class="form-control" type="date" name="entry_date" id="entry_date" value="{{ old('entry_date', $incomes->entry_date->toDateString()) }}" >
                        </div>
                        <div class="form-group">
                            <label class="required" for="amount">Biaya</label>
                            <input class="form-control" type="number" name="amount" id="amount" value="{{ old('amount', $incomes->amount) }}" placeholder="Contoh : 1000">
                        </div>
                        <div class="form-group">
                            <label for="description">Deskripsi</label>
                            <input class="form-control" type="text" name="description" id="description" value="{{ old('description', $incomes->description) }}">
                        </div>
                        <div class="form-actions mt-5">
                                <button class="btn btn-success" type="submit">
                                    <i class="far fa-save"> Simpan</i>
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    <i class="far fa-window-close"> Setel Ulang</i>
                                </button>
                                <a class="btn btn-dark" href="{{ route('incomes.index') }}">
                                    <i class="far fa-arrow-alt-circle-left"> Kembali </i>
                                </a>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/financialManagement/incomes/index.blade.php
@extends('layouts.dashboard')
@section('title', 'Pendapatan')
@section('content')
<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="mb-1 page-title text-truncate text-dark font-weight-medium">Pendapatan</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="p-0 m-0 breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('home.index')}}" class="text-muted">Beranda</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Pendapatan</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

@if(Session::has('success'))
<div class="page-breadcrumb">
    @include('layouts.flash-success',[ 'message'=> Session('success') ])
</div>
@endif

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Daftar Pendapatan</h4>
                    <div style="margin-bottom: 10px;" class="row">
                        <div class="col-lg-12">
                            <a class="btn btn-success" href="{{ route('incomes.create') }}">
                                <i class="far fa-plus-square"> Tambah Pendapatan</i>
                            </a>
                            <a class="btn btn-dark" href="{{ route('income.trash') }}">
                                <i class="far fa-trash-alt"> Tong Sampah</i>
                            </a>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table id="zero_config" class="table table-striped table-bordered no-wrap">
                            <thead>
                                <tr>
                                    <th>
                                        No
                                    </th>
                                    <th>
                                        Penanggung Jawab
                                    </th>
                                    <th>
                                        Kategori Pendapatan
                                    </th>
                                    <th>
                                        Tanggal
                                    </th>
                                    <th>
                                        Biaya (Rp)
                                    </th>
                                    <th>
                                        Deskripsi
                                    </th>
                                    <th class="text-center">
                                        Tindakan
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($incomes as $key => $income)
                                <tr>
                                    <td>
                                        {{ ++$no ?? '' }}
                                    </td>
                                    <td>
                                        {{$income->user->name ?? '' }}
                                    </td>
                                    <td>
                                        {{ $income->income_category->name ?? '' }}
                                    </td>
                                    <td>
                                        {{ $income->entry_date->toDateString() ?? '' }}
                                    </td>
                                    <td>
                                        Rp {{ number_format($income['amount'], 2) ?? ''}}
                                    </td>
                                    <td>
                                        {{ $income->description ?? '' }}
                                    </td>
                                    <td>
                                        <a class="btn btn-xs btn-warning text-white" href="{{ route('incomes.show',$income->id) }}"><i class="fas fa-eye"> Lihat</i></a>
                                        <a class="btn btn-xs btn-primary" href="{{ route('incomes.edit',$income->id) }}"><i class="far fa-edit"> Ubah</i></a>
                                        <form action="{{ route('incomes.destroy', $income->id) }}" method="POST" onsubmit="return confirm('Apakah anda yakin ?');" style="display: inline-block;">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                            <button type="submit" class="btn btn-danger"> <i class="far fa-window-close"> Pindah ke Tong Sampah</i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/financialManagement/incomes/show.blade.php
@extends('layouts.dashboard')
@section('title', 'Lihat Pendapatan')
@section('content')

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-7 align-self-center">
            <h4 class="page-title text-truncate text-dark font-weight-medium mb-1">Lihat Pendapatan</h4>
            <div class="d-flex align-items-center">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb m-0 p-0">
                        <li class="breadcrumb-item"><a href="{{ route('home.index')}}" class="text-muted">Beranda</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('incomes.index')}}" class="text-muted">Pendapatan</a></li>
                        <li class="breadcrumb-item text-muted active" aria-current="page">Lihat Pendapatan</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div style="margin-bottom: 10px;" class="row">
                        <div class="col-lg-12">
                   
                            <a class="btn btn-dark" href="{{ route('incomes.index') }}">
                                <i class="far fa-arrow-alt-circle-left"> Kembali </i>
                            </a>
                 
                        </div>
                    </div>

                    <table width="100%" class="table table-borderless">
                        <tr>
                            <td width="20%">Kategori Pengeluaran</td>
                            <td width="2%">:</td>
                            <td width="60%" class="font-weight-bold">{{ $income->income_category->name ?? '' }}</td>
                        </tr>
                        <tr>
                            <td width="20%">Tanggal</td>
                            <td width="2%">:</td>
                            <td width="60%" class="font-weight-bold">{{ $income->entry_date->toFormattedDateString() ?? '' }}</td>
                        </tr>
                        <tr>
                            <td width="20%">Biaya</td>
                            <td width="2%">:</td>
                            <td width="60%" class="font-weight-bold">{{ $income->amount ?? '' }}</td>
                        </tr>
                        <tr>
                            <td width="20%">Deskripsi</td>
                            <td width="2%">:</td>
                            <td width="60%" class="font-weight-bold">{{ $income->description ?? '' }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection